[package]
name = "neobrew"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
clap = { version = "4.5.57", features = ["derive"] }
color-eyre = "0.6.5"
enum_dispatch = "0.3.13"
figment = { version = "0.10.19", features = ["env"] }
futures = "0.3.31"
once_cell = "1.21.3"
proc-exit = "2.0.2"
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["macros", "process", "rt-multi-thread"] }
