[package]
name = "neobrew"
version = "0.1.0"
authors = ["Cheeshian Chuah (shian15810) <shian15810@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.102"
async-recursion = "1.1.1"
async-trait = "0.1.89"
bytes = "1.11.1"
cfg-if = "1.0.4"
clap = { version = "4.5.60", features = ["cargo", "derive"] }
enum_dispatch = "0.3.13"
etcetera = "0.11.0"
figment = { version = "0.10.19", features = ["env"] }
flate2 = "1.1.9"
foyer = "0.22.3"
futures = "0.3.32"
indoc = "2.0.7"
itertools = "0.14.0"
once_cell = "1.21.3"
proc-exit = "2.0.2"
reqwest = { version = "0.13.2", features = ["json", "stream"] }
serde = "1.0.228"
serde_json = "1.0.149"
sha2 = "0.10.9"
tar = "0.4.44"
tokio = { version = "1.49.0", features = ["process", "rt-multi-thread", "signal"] }
tokio-stream = "0.1.18"
tokio-util = { version = "0.7.18", features = ["io-util"] }
