[package]
name = "neobrew"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
async-recursion = "1.1.1"
async-trait = "0.1.89"
cfg-if = "1.0.4"
clap = { version = "4.5.57", features = ["derive"] }
enum_dispatch = "0.3.13"
figment = { version = "0.10.19", features = ["env"] }
foyer = { version = "0.22.3", features = ["serde"] }
futures = "0.3.31"
once_cell = "1.21.3"
proc-exit = "2.0.2"
reqwest = { version = "0.13.2", features = ["json"] }
serde = { version = "1.0.228", features = ["derive", "rc"] }
tokio = { version = "1.49.0", features = ["macros", "process", "rt-multi-thread"] }
