[package]
name = "neobrew"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
clap = { version = "4.5.57", features = ["derive"] }
enum_dispatch = "0.3.13"
figment = { version = "0.10.19", features = ["env"] }
once_cell = "1.21.3"
proc-exit = "2.0.2"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
