[package]
name = "neobrew"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
enum_dispatch = "0.3.13"
figment = { version = "0.10.19", features = ["env"] }
serde = { version = "1.0.228", features = ["derive"] }
